### ISSUE TITLE
encryptionScheme to return when no encryptionScheme is specified

### ISSUE THREAD

**Issue by mrstux** [joeyparrish/encrypted-media-encryption-scheme#2]
@joeyparrish looking good, I have a single concern at the moment:

>Even if the application does not specify an encryption scheme, MediaKeySystemAccess.getConfiguration() must fill in a supported value in the encryptionScheme fields of MediaKeySystemMediaCapability objects.

What if the user-agent supports two encryption schemes?
How does it pick which one to specify? 
What if it picks the wrong one from the applications perspective? 
Would it just specify its historic default? 
Or would it pick its preferred scheme, which may not be its historic scheme?

**Comment by joeyparrish** [comment]
If an application does not specify a scheme, and the user-agent supports two schemes, it would be up to the user-agent to pick one.  Since a "missing or null value indicates that any encryption scheme is acceptable", there is no wrong one to pick.

Applications that are aware of the field should always specify a scheme.

> Applications should specify encryption scheme(s) they require, since different encryption schemes are generally incompatible with one another. Asking for "any" encryption scheme is unrealistic. Defining null as "any scheme" is convenient for backward compatibility.

Since the use of `null` is only intended to define backward compatibility for applications that are unaware of the field, user-agents would need to pick their historical default to avoid breaking such applications.

Does this make sense?  Do you think I need to clarify some part of the explainer?

**Comment by mrstux** [comment]
>Applications which ignore this feature by leaving encryptionScheme null get the same user agent behavior they did before this feature existed: they have to assume what encryption schemes the user agent supports.

>Applications which don't use the new field will not be affected. If they make assumptions about the capabilities of certain platforms or key systems, they can continue to use those assumptions, with no additional risk.

>Any user agent which deprecates support for an existing encryption scheme could introduce backward compatibility issues for older applications which do not use this new feature

requestMediaKeySystemAccess returns a MediaKeySystemAccess object, for the first valid configuration, which defines a createMediaKeys method.

One thing I'm not sure on is if the encryptionScheme were automatically filled in as part of the returned MediaKeySystemConfiguration, does that mean that the created MediaKeys object created using that MediaKeySystemAccess object is locked to that encryptionScheme? Or is the encryptionScheme purely informative and has no effect on the createMediaKeys method?

If it were that the MediaKeys were locked to the encryptionScheme specified in the returned configuration, then in order to not break applications which are assuming current behaviour then the encryptionScheme in the `null` case better be the "historical default"

But, if the encryptionScheme is merely informative, then encryptionScheme could be the preferred encryptionScheme, which arguably could be more useful to application developers, rather than just confirming the historical default.

Basically, I'm not 100% certain if the encryptionScheme in the MediaKeySystemConfiguration has any baring on limiting the encryption schemes supported by the object returned by the createMediaKeys() method, or if the encryptionScheme is purely informative. Or is this actually user-agent defined behaviour? The user-agent presumably actually makes its pick on what to use when it receives the first init segment, but is that specified?

Is it valid to create a configuration with 'null', get back a MediaKeySystemAccess with a configuration of 'cenc' and then send in 'cbcs' content, if the user-agent does in fact support 'cbcs'?

I can see just that happening right now based on our actual code, where we detect Chrome 68, and may use CBCS, but when/if Chrome 68 supports encryptionScheme, then it would be 'null' and presumably choose/recommend 'cenc' as its default/preferred scheme.

**Comment by joeyparrish** [comment]
At the risk of over-simplifying your concern, it seems to boil down to this question:

If the app fails to specify a scheme, the UA returns 'cenc', and the UA supports both 'cenc' and 'cbcs', will the resulting CDM instance still be able to decrypt 'cbcs' content?  Does the returned value restrict the CDM or reflect an existing CDM restriction, or can the CDM decrypt with any supported scheme regardless of what was queried?

Please let me know if I have understood the question.  If so, I will discuss with some colleagues with more experience in implementation before I try to answer it.

**Comment by mrstux** [comment]
I think that is an accurate summary :)

**Comment by joeyparrish** [comment]
I've been discussing this with some folks involved in the Chrome implementation of EME to get some more insight into how things work in Chrome.

If my proposal gets implemented as it is written today, and an application does not specify an encryption scheme, it would be possible for a CDM instance to support more than just the encryption scheme returned by the API.  For example, the UA might return "cenc", but still be able to decrypt "cbcs".  But there would be no guarantee of that.  The UA might **only** support that one scheme.  Since the application didn't ask, it shouldn't assume.

I think I need to revise the explainer a bit.  I'm not sure it actually makes sense to return something when the app doesn't specify an encryption scheme.  Apps who **do** fill in `encryptionScheme` can still detect a lack of support in the browser by the fact that the field **doesn't** appear in the browser's response.  For a polyfill or application that needs to support both old and new EME implementations, that's the important part.

**Comment by mrstux** [comment]
I think that makes a lot of sense. Applications which do not specify an encryptionScheme would get the previous behaviour that they expect. Applications which do specify an encryptionScheme would be able to detect if the UA supported their request, or ignored it.

If a MediaKeySystemAccess object has an encryptionScheme attached to it, then the application will have to assume that that MediaKeySystemAccess is restricted to that scheme, even if it is not necessarily, as there is no guarantee from the UA.

And by removing the requirement on the UA to pick a scheme when none is specified, that also means the UA no longer has to implement unspecified logic for picking a scheme, it merely answers the query based on its capabilities.

A polyfill could easily fill in the encryptionScheme if it were not present, based on its existing user-agent based assumptions.

**Comment by joeyparrish** [comment]
I updated the explainer in a7471cee8a199c87c89c0b3b5a4c66008d251912, but forgot to tag the issue in the commit.  Please take a look at the latest and let me know if you think we can close this issue.

**Comment by mrstux** [comment]
I think we can close this issue. Thankyou @joeyparrish

**Comment by joeyparrish** [comment]
Thanks!
