### ISSUE TITLE
Be more explicit about supported patterns for CBCS

### ISSUE THREAD

**Issue by ddorwin** [joeyparrish/encrypted-media-encryption-scheme#7]
Does `"cbcs"` really allow for any pattern or are there limitations? Section 10.4 in ISO 23001-7:2016 contains at least one `SHOULD`, and one platform has historically only supported a specific pattern. This document should be more explicit on what is supported to facilitate interop on the web platform.

**Comment by joeyparrish** [comment]
@jernoble, can you comment on Safari's and FairPlay's capabilities in this regard?  Do they support only a single pattern, which should be specified for interop?  Or are they flexible enough to accept the range of what's specified in section 10.4 in ISO 23001-7:2016?

That seems to be the most important thing to establish before we make any changes to this proposal.

**Comment by jernoble** [comment]
@joeyparrish Sure thing. Safari's capabilities are exactly the same as the platform (iOS, macOS) on which it runs. And this is what I heard back from our platform team:

> 'cbcs' as defined by 23001-7 allows any pattern.
> 
> The FairPlay Streaming implementation of 'cbcs' on Apple devices however only supports 10% (for video) and 100% (for audio).
>

**Comment by joeyparrish** [comment]
Okay, then I suppose we need to be more specific.

**Comment by joeyparrish** [comment]
I updated the explainer with some additional information about the patterns that would be expected for interop.

**Comment by mwatson2** [comment]
Whilst it may be true that some implementations today are limited to a specific pattern, I don't think it should be a restriction in our specification. In particular the [AV1 ISO BMFF binding specification](https://aomedia.org/wp-content/uploads/2018/09/AV1-ISO-Base-Media-File-Format-Binding-Specification.pdf) explicitly requires support of any pattern. Since AV1 is new, implementations can be updated to support any pattern at the same time they are updated to support AV1.

**Comment by joeyparrish** [comment]
Fair enough.  Reverting the change.

**Comment by jpiesing** [comment]
> Whilst it may be true that some implementations today are limited to a specific pattern, I don't think it should be a restriction in our specification. In particular the [AV1 ISO BMFF binding specification](https://aomedia.org/wp-content/uploads/2018/09/AV1-ISO-Base-Media-File-Format-Binding-Specification.pdf) explicitly requires support of any pattern. Since AV1 is new, implementations can be updated to support any pattern at the same time they are updated to support AV1.

The proposed change may not have been quite right but I don't see why this issue has been closed and believe it should be re-opened.

If there are implementations out there that only support the Apple cbcs pattern then closing this issue without any change at all means those implementations will have to reply that they don't support 'cbcs' even if the content concerned is Apple cbcs pattern.

Please re-open this issue.

**Comment by joeyparrish** [comment]
@jpiesing, I'd love to have your thoughts on a solution.  What do you think we should do?

**Comment by jpiesing** [comment]
> @jpiesing, I'd love to have your thoughts on a solution. What do you think we should do?

You might consider having 'cbcs' as the the unrestricted encryption scheme and a second encryption scheme 'cbcs-10' or 'cbcs-restricted' or similar. If someone has content that is encrypted according to the Apple model then they can ask about 'cbcs-restricted' rather than 'cbcs' and they get a positive result on more UAs than they would asking about 'cbcs'.

**Comment by jpiesing** [comment]
> Safari's capabilities are exactly the same as the platform (iOS, macOS) on which it runs. And this is what I heard back from our platform team:
> 
> > 'cbcs' as defined by 23001-7 allows any pattern.
> > The FairPlay Streaming implementation of 'cbcs' on Apple devices however only supports 10% (for video) and 100% (for audio).

@jernoble: Does the cbcs 10% mode apply for both 'classic' HLS based on MPEG-2 transport stream and 'new' HLS based on CMAF? Apparently it's not mentioned in the spec for HLS/fMP4-CMAF. If it's only historical then perhaps it can be ignored?

**Comment by jernoble** [comment]
Again, from our platform team: Yes, the 10% pattern applies regardless of container format used for delivery.

**Comment by joeyparrish** [comment]
I've split cbcs and added "cbcs-restricted".  Thanks!

**Comment by joeyparrish** [comment]
I've had feedback from @xhwang-chromium that the language I'm using in the latest revision isn't specific enough, so I'm reopening this.

**Comment by joeyparrish** [comment]
I'm renaming "cbcs-restricted" to "cbcs-recommended" based on feedback from @xhwang-chromium, as well as improving the definitions of both cbcs modes.

**Comment by xhwang-chromium** [comment]
joeyparrish: Thanks!

Pasting my suggestions here for the full picture and context.

### Proposed change for the definition of “cbcs” and “cbcs-restricted”
- **cbcs**: The "cbcs" mode, defined in ISO 23001-7:2016, section 4.2d. AES-CBC mode partial video NAL pattern encryption. Different encryption patterns are allowed for video, while audio must be protected using whole-block full-sample encryption.
- **cbcs-restricted**: The same as "cbcs" mode, but with a specific encrypt:skip pattern of 1:9 for video, as recommended in ISO 23001-7:2016, section 10.4.2.

#### Notes:
- Use "**different** encryption patterns are allowed for video" instead of "**any** encryption patterns are allowed for video" because the spec does have restrictions on what patterns are allowed: crypt_byte_block + skip_byte_block SHOULD equal 10. For example 5:5 is a valid pattern, but 2:2 is not.

### Discussion on “cbcs-restricted” naming
**cbcs-restricted** is a bit confusing, as it's unclear what is restricted and how. Would the following be better?
- **cbcs-recommended**: Since the spec (10.4.2) says “An encrypt:skip pattern of 1:9 (i.e. 10% partial encryption) is recommended”. But "recommended" could be confusing as it's unclear what it means without looking at the definition. Also people could read it as it's recommended by the user agent, e.g. for best performance or security etc, which is not necessarily the case.
- **cbcs-1-9** or **cbcs-1-9-pattern-for-video**: to be explicit about how it’s restricted. It's a bit hard to read, but is technically clear and doesn't imply any subjective opinion (e.g. good or bad, as in recommended or restricted). 

At the time of writing I feel I favor "cbcs-1-9*" more than "cbcs-recommended".

Any suggestions or comments?

**Comment by joeyparrish** [comment]
> Use "**different** encryption patterns are allowed for video" instead of "**any** encryption patterns are allowed for video" because the spec does have restrictions on what patterns are allowed: crypt_byte_block + skip_byte_block SHOULD equal 10. For example 5:5 is a valid pattern, but 2:2 is not.

Thank you for pointing this out.  I'll make some changes to correct this, both here and in my EME PR.  I find your term "different encryption patterns" to be vague, so I'll be explicit that any pattern permitted by ISO 23001-7 is allowed.

> At the time of writing I feel I favor "cbcs-1-9*" more than "cbcs-recommended".

I think I prefer "recommended", given that we spell out what that means.  But I'd be open to feedback on that if others feel strongly about it.  I don't expect that we will want to add names to indicate additional specific patterns, since that would imply devices which only accept one pattern that isn't the recommended one.  So I'm not worried about naming conflicts.

**Comment by xhwang-chromium** [comment]
Thanks! I left some comments in the PR.

**Comment by joeyparrish** [comment]
After @gregwfreedman came down in favor of `cbcs-1-9` as well, and pointed out that the "recommended" version could change, I went ahead and switched from `cbcs-recommended` to `cbcs-1-9`.
